// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./components/layout/Header";
// import Footer from "./components/layout/Footer";
// import ServicePolicies from "./(home)/ServicePolicies";
// import { Toaster } from "react-hot-toast";
// import { ReduxProvider } from "./ReduxProvider";
// import CartModal from "./components/CartModal";
// import { ThemeProvider } from "@/components/ThemeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         suppressHydrationWarning
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ReduxProvider>
//           <Header />
//           <ThemeProvider>{children}</ThemeProvider>
//           <CartModal />

//           <Toaster position="top-right" reverseOrder={false} />
//           <ServicePolicies />
//           <Footer />
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }


// app/layout.js (Updated)
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./components/layout/Header";
// import Footer from "./components/layout/Footer";
// import ServicePolicies from "./(home)/ServicePolicies";
// import { Toaster } from "react-hot-toast";
// import { ReduxProvider } from "./ReduxProvider";
// import CartModal from "./components/CartModal";
// import { ThemeProvider } from "@/components/ThemeProvider";
// import { fetchSEOSettings } from "@/lib/seo";
// import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // Dynamic metadata for layout
// export async function generateMetadata() {
//   const seoSettings = await fetchSEOSettings();
  
//   return {
//     title: {
//       default: `${seoSettings.data.website_name} | ${seoSettings.data.site_motto}`,
//       template: `%s | ${seoSettings.data.website_name}`
//     },
//     description: seoSettings.data.meta_description,
//     keywords: seoSettings.data.meta_keywords,
//     metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL),
//     openGraph: {
//       title: seoSettings.data.meta_title,
//       description: seoSettings.data.meta_description,
//       images: [seoSettings.data.meta_image],
//       siteName: process.env.NEXT_PUBLIC_APP_NAME,
//     },
//     twitter: {
//       card: 'summary_large_image',
//       title: seoSettings.data.meta_title,
//       description: seoSettings.data.meta_description,
//       images: [seoSettings.data.meta_image],
//     },
//   };
// }

// export default async function RootLayout({ children }) {
//   const seoSettings = await fetchSEOSettings();
  
//   return (
//     <html lang="en">
//       <head>
//         {/* CSRF Token and App URLs - Similar to Laravel */}
//         <meta name="csrf-token" content={process.env.NEXT_PUBLIC_CSRF_TOKEN || ""} />
//         <meta name="app-url" content={process.env.NEXT_PUBLIC_API_URL} />
//         <meta name="file-base-url" content={process.env.NEXT_PUBLIC_FILE_BASE_URL} />
        
//         {/* Favicon */}
//         <link rel="icon" href={seoSettings.data.site_icon} />
//         <link rel="apple-touch-icon" href={seoSettings.data.site_icon} />
        
      
//       </head>
//       <body
//         suppressHydrationWarning
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ReduxProvider>
//           <Header />
//           <ThemeProvider>{children}</ThemeProvider>
//           <CartModal />
//           <Toaster position="top-right" reverseOrder={false} />
//           <ServicePolicies />
//           <Footer />
//         </ReduxProvider>
        
//         {/* User login state script */}
//         <Script
//           id="user-state"
//           strategy="beforeInteractive"
//           dangerouslySetInnerHTML={{
//             __html: `
//               window.isLoggedIn = false; // You'll set this from your auth state
//             `,
//           }}
//         />
//       </body>
//     </html>
//   );
// }


// // app/layout.js
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./components/layout/Header";
// import Footer from "./components/layout/Footer";
// import ServicePolicies from "./(home)/ServicePolicies";
// import { Toaster } from "react-hot-toast";
// import { ReduxProvider } from "./ReduxProvider";
// import CartModal from "./components/CartModal";
// import { ThemeProvider } from "@/components/ThemeProvider";
// import { fetchSEOSettings } from "@/lib/seo";
// import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // Dynamic metadata for layout
// export async function generateMetadata() {
//   try {
//     const seoSettings = await fetchSEOSettings();
    
//     if (seoSettings && seoSettings.success && seoSettings.data) {
//       const data = seoSettings.data;
      
//       return {
//         title: {
//           default: `${data.website_name} | ${data.site_motto}`,
//           template: `%s | ${data.website_name}`
//         },
//         description: data.meta_description,
//         keywords: data.meta_keywords,
//         metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://dev.nisamirrorfashionhouse.com'),
//         openGraph: {
//           title: data.meta_title,
//           description: data.meta_description,
//           images: [data.meta_image],
//           siteName: data.website_name,
//         },
//         twitter: {
//           card: 'summary_large_image',
//           title: data.meta_title,
//           description: data.meta_description,
//           images: [data.meta_image],
//         },
//       };
//     }
//   } catch (error) {
//     console.error("Error generating metadata:", error);
//   }
  
//   // Fallback metadata if API fails
//   return {
//     title: {
//       default: "Soft Commerce | Be Your Own Label",
//       template: "%s | Soft Commerce"
//     },
//     description: "Shop the latest trends at Soft Commerce. Quality products with fast delivery.",
//     keywords: "ecommerce, shopping, online store",
//     metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://dev.nisamirrorfashionhouse.com'),
//     openGraph: {
//       title: "Soft Commerce",
//       description: "Shop the latest trends",
//       images: ["/default-og-image.jpg"],
//       siteName: "Soft Commerce",
//     },
//     twitter: {
//       card: 'summary_large_image',
//       title: "Soft Commerce",
//       description: "Shop the latest trends",
//       images: ["/default-og-image.jpg"],
//     },
//   };
// }

// export default async function RootLayout({ children }) {
//   let seoSettings = null;
//   let siteIcon = "/favicon.ico";
  
//   try {
//     const result = await fetchSEOSettings();
//     if (result && result.success && result.data) {
//       seoSettings = result.data;
//       siteIcon = seoSettings.site_icon || "/favicon.ico";
//     }
//   } catch (error) {
//     console.error("Error fetching SEO settings for layout:", error);
//   }
  
//   return (
//     <html lang="en">
//       <head>
//         <meta name="csrf-token" content={process.env.NEXT_PUBLIC_CSRF_TOKEN || ""} />
//         <meta name="app-url" content={process.env.NEXT_PUBLIC_API_URL || "/api/v2"} />
//         <meta name="file-base-url" content={process.env.NEXT_PUBLIC_FILE_BASE_URL || "https://dev.nisamirrorfashionhouse.com/public"} />
        
//         <link rel="icon" href={siteIcon} />
//         <link rel="apple-touch-icon" href={siteIcon} />
// {/*         
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
//         <link 
//           href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" 
//           rel="stylesheet"
//         /> */}
        
//         <style>
//           {`
//             .z-3000 {
//               z-index: 3000;
//             }
//           `}
//         </style>
//       </head>
//       <body
//         suppressHydrationWarning
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ReduxProvider>
//           <Header />
//           <ThemeProvider>{children}</ThemeProvider>
//           <CartModal />
//           <Toaster position="top-right" reverseOrder={false} />
//           <ServicePolicies />
//           <Footer />
//         </ReduxProvider>
        
//         <Script
//           id="user-state"
//           strategy="beforeInteractive"
//           dangerouslySetInnerHTML={{
//             __html: `
//               window.isLoggedIn = false;
//             `,
//           }}
//         />
//       </body>
//     </html>
//   );
// }

// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutDetector from "@/components/LayoutDetector";
import { ReduxProvider } from "./ReduxProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import { fetchSEOSettings } from "@/lib/seo";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Dynamic metadata for layout
export async function generateMetadata() {
  try {
    const seoSettings = await fetchSEOSettings();
    
    if (seoSettings && seoSettings.success && seoSettings.data) {
      const data = seoSettings.data;
      
      return {
        title: {
          default: `${data.website_name} | ${data.site_motto}`,
          template: `%s | ${data.website_name}`
        },
        description: data.meta_description,
        keywords: data.meta_keywords,
        metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://dev.nisamirrorfashionhouse.com'),
        openGraph: {
          title: data.meta_title,
          description: data.meta_description,
          images: [data.meta_image],
          siteName: data.website_name,
        },
        twitter: {
          card: 'summary_large_image',
          title: data.meta_title,
          description: data.meta_description,
          images: [data.meta_image],
        },
      };
    }
  } catch (error) {
    console.error("Error generating metadata:", error);
  }
  
  // Fallback metadata if API fails
  return {
    title: {
      default: "Soft Commerce | Be Your Own Label",
      template: "%s | Soft Commerce"
    },
    description: "Shop the latest trends at Soft Commerce. Quality products with fast delivery.",
    keywords: "ecommerce, shopping, online store",
    metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://dev.nisamirrorfashionhouse.com'),
    openGraph: {
      title: "Soft Commerce",
      description: "Shop the latest trends",
      images: ["/default-og-image.jpg"],
      siteName: "Soft Commerce",
    },
    twitter: {
      card: 'summary_large_image',
      title: "Soft Commerce",
      description: "Shop the latest trends",
      images: ["/default-og-image.jpg"],
    },
  };
}

export default async function RootLayout({ children }) {
  let seoSettings = null;
  let siteIcon = "/favicon.ico";
  
  try {
    const result = await fetchSEOSettings();
    if (result && result.success && result.data) {
      seoSettings = result.data;
      siteIcon = seoSettings.site_icon || "/favicon.ico";
    }
  } catch (error) {
    console.error("Error fetching SEO settings for layout:", error);
  }
  
  return (
    <html lang="en">
      <head>
        <meta name="csrf-token" content={process.env.NEXT_PUBLIC_CSRF_TOKEN || ""} />
        <meta name="app-url" content={process.env.NEXT_PUBLIC_API_URL || "/api/v2"} />
        <meta name="file-base-url" content={process.env.NEXT_PUBLIC_FILE_BASE_URL || "https://dev.nisamirrorfashionhouse.com/public"} />
        
        <link rel="icon" href={siteIcon} />
        <link rel="apple-touch-icon" href={siteIcon} />
        
        <style>
          {`
            .z-3000 {
              z-index: 3000;
            }
          `}
        </style>
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <ThemeProvider>
            <LayoutDetector>
              {children}
            </LayoutDetector>
          </ThemeProvider>
        </ReduxProvider>
        
        <Script
          id="user-state"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.isLoggedIn = false;
            `,
          }}
        />
      </body>
    </html>
  );
}